# ExternalDNS: Kustomization (DEV)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.14.3  # 최신 버전 확인 필요
    releaseName: external-dns
    namespace: kube-system
    valuesFile: ../../values/external-dns.values.yaml

commonLabels:
  app.kubernetes.io/part-of: kyeol-platform
  environment: dev
