provider: aws
aws:
  region: ap-northeast-2
domainFilters:
  - kyeol.click
txtOwnerId: kyeol-dev
policy: sync
serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::827913617839:role/kyeol-dev-external-dns-role
fullnameOverride: external-dns
