# ExternalDNS Addon - PROD
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.14.3
    releaseName: external-dns
    namespace: kube-system
    valuesFile: ../../values/external-dns.values.yaml
